name: Build Android Java APK & Create Release
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Application with Gradle
        run: |
          chmod +x gradlew || true
          ./gradlew assembleDebug --no-daemon

      - name: Create Automatic Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Prajapati Browser Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            **/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
