name: Build Android Java APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Application with Gradle
        run: |
          chmod +x gradlew || true
          gradle assembleDebug --no-daemon

      - name: Upload APK Artifact Target
        uses: actions/upload-artifact@v4
        with:
          name: Prajapati-Core-Browser
          path: "**/build/outputs/apk/debug/*.apk"
          
